use classicmodels;
show tables;

-- Q1. SELECT clause with WHERE, AND, DISTINCT, Wild Card (LIKE)
-- a) Fetch the employee number, first name and last name of those employees who are working as Sales Rep 
-- reporting to employee with employeenumber 1102 (Refer employee table)
select * from employees;
select employeeNumber, firstName, lastName 
from employees 
where jobTitle = "Sales Rep" AND reportsTo = 1102;
-- b) Show the unique productline values containing the word cars at the end from the products table.
select * from products;
select distinct productLine 
from products 
where productLine LIKE "%Cars";

-- Q2. CASE STATEMENTS for Segmentation
-- a) Using a CASE statement, segment customers into three categories based on their country:(Refer Customers table)
-- "North America" for customers from USA or Canada
-- "Europe" for customers from UK, France, or Germany
-- "Other" for all remaining countries
-- Select the customerNumber, customerName, and the assigned region as "CustomerSegment".
select *from customers;
select customerNumber, customerName, 
	case
		when country IN ('USA', 'Canada') THEN "North America"
		when country in ('UK', 'France', 'Germany') THEN "Europe"
		else "Other"
	End AS CustomerSegment
from customers;

-- Q3. Group By with Aggregation functions and Having clause, Date and Time functions
-- a) Using the OrderDetails table, identify the top 10 products (by productCode) with the highest total order quantity across all orders.
select * from OrderDetails;
select productCode, SUM(quantityOrdered) as total_ordered
from OrderDetails
group by productCode
order by total_ordered DESC
limit 10;
-- b) Company wants to analyse payment frequency by month. 
-- Extract the month name from the payment date to count the total number of payments for each month 
-- and include only those months with a payment count exceeding 20. 
-- Sort the results by total number of payments in descending order.  (Refer Payments table). 
SELECT *FROM payments;
SELECT Monthname(paymentDate) as payment_month, COUNT(*) AS num_payments
FROM payments
GROUP BY payment_month
HAVING num_payments > 20
order by num_payments DESC;

-- Q5. JOINS
-- a) List the top 5 countries (by order count) that Classic Models ships to. (Use the Customers and Orders tables)
USE classicmodels;
select* from customers;
select * from orders;
SELECT c.country, COUNT(o.orderNumber) as order_count
from customers c join orders o 
ON c.customerNumber = o.customerNumber
GROUP BY c.country 
ORDER BY order_count DESC
LIMIT 5;

-- Q8. Views in SQL
-- a) Create a view named product_category_sales that provides insights into sales performance by product category. This view should include the following information:
-- 		productLine: The category name of the product (from the ProductLines table).
-- 		total_sales: The total revenue generated by products within that category (calculated by summing the orderDetails.quantity * orderDetails.priceEach for each product in the category).
-- 		number_of_orders: The total number of orders containing products from that category.
-- (Hint: Tables to be used: Products, orders, orderdetails and productlines)
SELECT * FROM Products;
SELECT * FROM orders;
SELECT * FROM orderdetails;
SELECT * FROM productlines;
CREATE VIEW product_category_sales AS
SELECT 
    p.productLine, 
    SUM(od.quantityOrdered * od.priceEach) AS total_sales, 
    COUNT(DISTINCT o.orderNumber) AS number_of_orders
FROM productlines pl
JOIN products p ON pl.productLine = p.productLine
JOIN orderdetails od ON p.productCode = od.productCode
JOIN orders o ON od.orderNumber = o.orderNumber
GROUP BY p.productLine;

SELECT * FROM product_category_sales;

-- Q9. Stored Procedures in SQL with parameters
-- a) Create a stored procedure Get_country_payments which takes in year and country as inputs and gives year wise, country wise total amount as an output. Format the total amount to nearest thousand unit (K)
-- Tables: Customers, Payments
SELECT * FROM Customers;
SELECT * FROM Payments;
CALL Get_country_payments(2003, "France")





